version:          "3.7"

services:
  # main app container
  sensors:
    build:
      context:    ./services/HomeSensors
      dockerfile: Dockerfile
    privileged:   true
    restart:      always
    volumes:
      - "./services/HomeSensors:/home/HomeSensors/app"
    ports:
      - 5001:5000
    env_file:
      - app.env

    depends_on:
      - sensors-db
      - rmq
  # Celery worker
  worker:
    build:
      context:    ./services/HomeSensors/
      dockerfile: Dockerfile
    privileged:   true
    entrypoint: celery
    command: -A celery_worker worker --loglevel=info -B
    volumes:
      - "./services/HomeSensors:/home/HomeSensors/app"
    env_file:
      - app.env
    depends_on:
      - rmq
      - sensors-db
  # Celery flower
  flower:
    build:
      context:    ./services/HomeSensors/app/flower
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    env_file:
      - app.env
  # DB Container
  sensors-db:
    build:
      context:    ./services/HomeSensors/app/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    volumes:
      - "db-data:/var/lib/postgresql/data"
    env_file:
      - app.env
  nginx:
    build:
      context:    ./services/nginx
      dockerfile: Dockerfile
    restart:      always
    ports:
      - 80:80
    depends_on:
      - sensors

  rmq:
    image:        rabbitmq:3-management
    env_file:
      - app.env
    ports:
      - 15672:15672

volumes:
  db-data:
