version:          "3.7"

services:
  sensors:
    build:
      context:    ./services/HomeSensors
      dockerfile: Dockerfile
    privileged:   true
    restart:      always
    volumes:
      - "./services/HomeSensors:/home/HomeSensors/app"
    ports:
      - 5001:5000
    env_file:
      - app.env

    depends_on:
      - sensors-db
      - rmq
  sensors-db:
    build:
      context:    ./services/HomeSensors/app/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    env_file:
      - app.env
  nginx:
    build:
      context:    ./services/nginx
      dockerfile: Dockerfile
    restart:      always
    ports:
      - 80:80
    depends_on:
      - sensors

  rmq:
    image:          rabbitmq:3-management
    env_file:
      - app.env
    ports:
      - 15672:15672
