""" hour to Data Model

Revision ID: 169710108c46
Revises: a6ad14a4422a
Create Date: 2019-10-10 18:19:26.735453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '169710108c46'
down_revision = 'a6ad14a4422a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ldr', 'hour')
    op.drop_column('temp_hum', 'hour')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_hum', sa.Column('hour', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('ldr', sa.Column('hour', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
