"""FIX BUG hour to Data Model

Revision ID: 1da2c0db876b
Revises: 169710108c46
Create Date: 2019-10-10 18:20:18.912186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da2c0db876b'
down_revision = '169710108c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ldr', sa.Column('hour', sa.Integer(), nullable=True))
    op.add_column('temp_hum', sa.Column('hour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_hum', 'hour')
    op.drop_column('ldr', 'hour')
    # ### end Alembic commands ###
