"""Add write_to_db variable to sensor model.

Revision ID: 424fc34e3b21
Revises: 1da2c0db876b
Create Date: 2019-10-14 13:47:40.178000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '424fc34e3b21'
down_revision = '1da2c0db876b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('read_frequency', sa.Float(precision=32), nullable=True))
    op.add_column('sensors', sa.Column('write_to_db', sa.Float(precision=32), nullable=True))
    op.drop_column('sensors', 'frequency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('frequency', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('sensors', 'write_to_db')
    op.drop_column('sensors', 'read_frequency')
    # ### end Alembic commands ###
